# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LgF13eFBLuVlIPBaOQKWY96gp6i80rU
"""

import pandas as pd
df = pd.read_csv(r'/content/customer_shopping_behavior(1).csv')

df.head()

df.info()

df.describe()

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ',"_")
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

#create a column age_group
labels = ['young adult','adult','middle-aged','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

df[['age','age_group']]

# Replace 'frequency' with the exact name of your column
distinct_values = df['frequency_of_purchases'].unique()

print(distinct_values)

#create a column purchase_frequency-days

frequency_mapping = {
    'Weekly': 7,
    'Monthly': 30,
    'Fortnightly': 14,
    'Bi-weekly': 14,
    'Annually': 365,
    'Quarterly': 90,
    'Every 3 Months': 90
    }
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['frequency_of_purchases','purchase_frequency_days']]

df[['discount_applied','promo_code_used']]

(df['discount_applied'] == df['promo_code_used']).all()

df = df.drop('promo_code_used', axis =1 )
df.columns

import sqlite3

# This creates a file named 'shopping_data.db' in your folder
conn = sqlite3.connect('shopping_data.db')

# 'customers' will be the name of the table inside the database
# 'con' is the connection we just made
# 'if_exists' ensures it doesn't error out if you run this twice
df.to_sql('customers', conn, if_exists='replace', index=False)

print("Table successfully stored in the database!")

# Let's read it back from the database to make sure it's there
query = "SELECT * FROM customers LIMIT 5"
check_df = pd.read_sql(query, conn)

print(check_df)

conn.close()